spring:
  application:
    name: my-project-backend
  security:
    jwt:
      key: abcdefghijk
      expire: 7
  data:
    redis:
      port: 6379
      database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/xxx
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: xxx@163.com
    password: xxx
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
websocket:
  port: 8888
  heartbeat-timeout: 6
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
